import Phaser from "phaser";

/**
 * 8-direction kid character.
 *
 * The spritesheet `public/assets/kid.png` is generated by
 * `tools/slice_kid_sheet.py` from the original presentation sheet
 * (`tools/kid_sheet_source.png`). Layout: 22 frames per row, one row per
 * direction (E, SE, S, SW, W, NW, N, NE), each frame 80x100 px with the
 * feet on y = 96 and the head centred on x = 40. Columns per row:
 *   0-3 idle, 4-11 walk, 12-15 breathing, 16-21 tag (arm reach).
 */
export const KID_TEXTURE = "kid";
export const KID_URL = `${import.meta.env.BASE_URL}assets/kid.png`;

const FRAME_W = 80;
const FRAME_H = 100;
const BASELINE_Y = 96;
const COLUMNS = 22;

/** Order of the direction rows in the sheet (clockwise from east, y down). */
export const KID_DIRECTIONS = ["E", "SE", "S", "SW", "W", "NW", "N", "NE"] as const;
export type KidDirection = (typeof KID_DIRECTIONS)[number];

const ANIM = {
  idle: { start: 0, count: 4 },
  walk: { start: 4, count: 8 },
  breathe: { start: 12, count: 4 },
  tag: { start: 16, count: 6 },
} as const;
type AnimName = keyof typeof ANIM;

/** Art is ~89px tall inside the 100px frame; scale to ~64px on screen. */
const KID_SCALE = 0.72;
/** Feet sit this far below the player's (server) centre, as a fraction of its radius. */
const FEET_OFFSET_RADII = 0.9;
/** How far the kid lunges forward during the tag swing (world px). */
const TAG_LUNGE = 10;

const WALK_FPS = 10;
const RUN_FPS = 16;

export function preloadKid(scene: Phaser.Scene) {
  scene.load.spritesheet(KID_TEXTURE, KID_URL, {
    frameWidth: FRAME_W,
    frameHeight: FRAME_H,
  });
}

function animKey(name: AnimName, dir: KidDirection) {
  return `kid-${name}-${dir}`;
}

/** Register all kid animations once per game (idempotent). */
export function createKidAnimations(scene: Phaser.Scene) {
  KID_DIRECTIONS.forEach((dir, row) => {
    const frame = (i: number) => row * COLUMNS + i;
    const range = (name: AnimName) =>
      Array.from({ length: ANIM[name].count }, (_, i) => ({
        key: KID_TEXTURE,
        frame: frame(ANIM[name].start + i),
      }));

    const add = (config: Phaser.Types.Animations.Animation) => {
      if (!scene.anims.exists(config.key!)) scene.anims.create(config);
    };

    add({ key: animKey("walk", dir), frames: range("walk"), frameRate: WALK_FPS, repeat: -1 });
    add({ key: animKey("breathe", dir), frames: range("breathe"), frameRate: 4, repeat: -1 });
    add({ key: animKey("idle", dir), frames: range("idle"), frameRate: 4, repeat: -1 });

    // Tag swing: neutral, wind-up, reach, MOST extended (held), reach, recover.
    // The extra `duration` on the 4th frame holds the arm fully outstretched
    // so the reach reads clearly at game speed.
    const tagFrames = range("tag").map((f, i) => ({
      ...f,
      duration: i === 3 ? 170 : i === 2 || i === 4 ? 30 : 0,
    }));
    add({ key: animKey("tag", dir), frames: tagFrames, frameRate: 16, repeat: 0 });
  });
}

/** Map a facing angle in radians (atan2(dy, dx), screen coords) to a direction. */
export function directionFromAngle(angle: number): KidDirection {
  const octant = Math.round(angle / (Math.PI / 4));
  return KID_DIRECTIONS[((octant % 8) + 8) % 8];
}

export type KidRole = "self" | "it" | "bot" | "human";

const ROLE_COLORS: Record<KidRole, number> = {
  self: 0x38bdf8, // blue
  it: 0xef4444, // red
  bot: 0xa78bfa, // purple
  human: 0xf59e0b, // amber
};

/**
 * One on-screen kid: sprite + coloured ground ring + name label.
 * `x`/`y` are the logical (server) position; the sprite is drawn with its
 * feet slightly below that point and depth-sorted by y.
 */
export class KidAvatar {
  readonly sprite: Phaser.GameObjects.Sprite;
  /** Coloured ellipse under the feet; stays at the logical position (camera target). */
  readonly shadow: Phaser.GameObjects.Ellipse;
  readonly label: Phaser.GameObjects.Text;

  x: number;
  y: number;
  facing = Math.PI / 2; // face the camera (south) until we know better
  moving = false;
  running = false;

  private role: KidRole | null = null;
  private tagging = false;
  private tagFacing: number | null = null;
  private lunge = { t: 0 };
  private lungeTween: Phaser.Tweens.Tween | null = null;
  private readonly feetOffset: number;

  /**
   * @param radius the player's collision radius on the server; sizes the
   *   ground ring and places the feet just below the logical centre.
   */
  constructor(
    private readonly scene: Phaser.Scene,
    x: number,
    y: number,
    radius: number,
    labelText: string,
    labelSize = "12px"
  ) {
    this.x = x;
    this.y = y;
    this.feetOffset = radius * FEET_OFFSET_RADII;

    this.shadow = scene.add.ellipse(x, y + this.feetOffset, radius * 2, radius * 0.75, 0x000000, 0.45);
    this.shadow.setDepth(1);

    this.sprite = scene.add.sprite(x, y + this.feetOffset, KID_TEXTURE, 2 * COLUMNS + ANIM.breathe.start);
    this.sprite.setOrigin(0.5, BASELINE_Y / FRAME_H);
    this.sprite.setScale(KID_SCALE);

    this.label = scene.add
      .text(x, y, labelText, {
        fontFamily: "system-ui, sans-serif",
        fontSize: labelSize,
        color: "#ffffff",
        stroke: "#10131a",
        strokeThickness: 4,
      })
      .setOrigin(0.5, 1);

    this.sprite.on(
      Phaser.Animations.Events.ANIMATION_COMPLETE,
      (anim: Phaser.Animations.Animation) => {
        if (anim.key.startsWith("kid-tag-")) this.endTag();
      }
    );

    this.update();
  }

  setRole(role: KidRole) {
    if (role === this.role) return;
    this.role = role;
    const color = ROLE_COLORS[role];
    this.shadow.setFillStyle(color, 0.35);
    this.shadow.setStrokeStyle(2, color, 0.95);
    // A light red wash on the kid makes IT readable even without the ring.
    if (role === "it") this.sprite.setTint(0xffc4c4);
    else this.sprite.clearTint();
  }

  setLabel(text: string) {
    if (this.label.text !== text) this.label.setText(text);
  }

  /**
   * Play the tag (arm reach) animation once. `towardAngle`, if given, turns
   * the kid to face the tagged player for the duration of the swing so the
   * arm reaches toward them.
   */
  playTag(towardAngle?: number) {
    if (this.tagging) return;
    this.tagging = true;
    this.tagFacing = towardAngle ?? null;

    const dir = directionFromAngle(this.tagFacing ?? this.facing);
    this.sprite.anims.play(animKey("tag", dir), true);

    // Small forward lunge in the facing direction, synced to the reach.
    this.lungeTween?.stop();
    this.lunge.t = 0;
    this.lungeTween = this.scene.tweens.add({
      targets: this.lunge,
      t: 1,
      duration: 190,
      delay: 90,
      ease: "Quad.easeOut",
      yoyo: true,
      hold: 120,
      onComplete: () => {
        this.lunge.t = 0;
      },
    });
  }

  get isTagging() {
    return this.tagging;
  }

  private endTag() {
    this.tagging = false;
    this.tagFacing = null;
  }

  /** Call every frame after updating x/y/facing/moving/running. */
  update() {
    const facing = this.tagFacing ?? this.facing;
    const dir = directionFromAngle(facing);

    if (!this.tagging) {
      if (this.moving) {
        const key = animKey("walk", dir);
        const current = this.sprite.anims.currentAnim?.key;
        if (current !== key) {
          // Keep the stride phase when only the direction changes.
          const progress = current?.startsWith("kid-walk-")
            ? this.sprite.anims.getProgress()
            : 0;
          this.sprite.anims.play(key);
          if (progress) this.sprite.anims.setProgress(progress);
        }
        this.sprite.anims.timeScale = this.running ? RUN_FPS / WALK_FPS : 1;
      } else {
        this.sprite.anims.play(animKey("breathe", dir), true);
        this.sprite.anims.timeScale = 1;
      }
    } else {
      this.sprite.anims.timeScale = 1;
    }

    const lunge = TAG_LUNGE * this.lunge.t;
    const lx = Math.cos(facing) * lunge;
    const ly = Math.sin(facing) * lunge * 0.6;

    const feetY = this.y + this.feetOffset;
    this.shadow.setPosition(this.x, feetY);
    this.sprite.setPosition(this.x + lx, feetY + ly);
    // Lower on screen = drawn in front.
    this.sprite.setDepth(10 + feetY / 10);
    this.label.setPosition(this.x, feetY - FRAME_H * KID_SCALE * 0.9 - 2);
    this.label.setDepth(1000 + feetY / 10);
  }

  destroy() {
    this.lungeTween?.stop();
    this.sprite.destroy();
    this.shadow.destroy();
    this.label.destroy();
  }
}
