import Phaser from "phaser";
import { DEFAULT_SKIN, SKINS, SKIN_IDS, type Skin, type SkinSheet } from "./skins";
import { DIRECTIONS, nextAvatarAnim, type Direction } from "./tagging";

export { directionFromAngle } from "./tagging";

/**
 * 8-direction kid character.
 *
 * The spritesheet `public/assets/kid.png` is generated by
 * `tools/slice_kid_sheet.py` from the original presentation sheet
 * (`tools/kid_sheet_source.png`). Layout: 30 frames per row, one row per
 * direction (E, SE, S, SW, W, NW, N, NE), each frame 80x100 px with the
 * feet on y = 96 and the head centred on x = 40. Columns per row:
 *   0-3 idle (static), 4-11 walk, 12-15 breathing (used as idle),
 *   16-21 tag (arm reach), 22-29 run (generated: big stride + arm swing).
 *
 * Skins (see skins.ts) use the same layout; Banana James
 * (`kid_banana.png`, from tools/make_banana_skin.py) has taller frames.
 * Tuxedo James (`kid_tuxedo.png`, from tools/make_tuxedo_skin.py) is a
 * recolour of this sheet, so it keeps the same frame size and feet line.
 * Pirate James (`kid_pirate.png`, from tools/make_pirate_skin.py) has padded
 * frames (tricorn hat on top, cutlass at the sides).
 * Pharaoh James (`kid_pharaoh.png`, from tools/make_pharaoh_skin.py) has
 * padded frames (nemes crown on top, cape flared at the sides).
 * Animation keys are `<texture>-<anim>-<dir>`, e.g. `kid_banana-walk-SE`.
 */
const FRAME_W = 80;
/** Height of the default (James) frame; art sizes below are relative to it. */
const FRAME_H = 100;
const COLUMNS = 30;

/** Order of the direction rows in the sheet (clockwise from east, y down). */
export const KID_DIRECTIONS = DIRECTIONS;
export type KidDirection = Direction;

const ANIM = {
  idle: { start: 0, count: 4 },
  walk: { start: 4, count: 8 },
  breathe: { start: 12, count: 4 },
  tag: { start: 16, count: 6 },
  run: { start: 22, count: 8 },
} as const;
type AnimName = keyof typeof ANIM;

/** Art is ~89px tall inside the 100px frame; scale to ~75px on screen. */
const KID_SCALE = 0.84;
/**
 * The ground ring, feet offset and lunge were tuned for the original 0.72
 * scale (~64px kid); grow them with the sprite so everything stays in
 * proportion. Display only: the server collision radius is unchanged.
 */
const SIZE = KID_SCALE / 0.72;
/** Feet sit this far below the player's (server) centre, as a fraction of its radius. */
const FEET_OFFSET_RADII = 0.9 * SIZE;
/** How far the kid lunges forward during the tag swing (world px). */
const TAG_LUNGE = 10 * SIZE;

const WALK_FPS = 10;
const RUN_FPS = 15;

/** Load every skin's spritesheet. */
export function preloadKid(scene: Phaser.Scene) {
  for (const id of SKIN_IDS) {
    const sheet = SKINS[id];
    scene.load.spritesheet(sheet.texture, sheet.url, {
      frameWidth: sheet.frameWidth,
      frameHeight: sheet.frameHeight,
    });
  }
}

function animKey(name: AnimName, dir: KidDirection, skin: Skin = DEFAULT_SKIN) {
  return `${SKINS[skin].texture}-${name}-${dir}`;
}

/** Animation name ("walk", "tag", ...) of a key made by animKey. */
function animOf(key: string | undefined): string | undefined {
  return key?.split("-")[1];
}

/** Register all kid animations for every skin once per game (idempotent). */
export function createKidAnimations(scene: Phaser.Scene) {
  for (const id of SKIN_IDS) createSkinAnimations(scene, SKINS[id]);
}

function createSkinAnimations(scene: Phaser.Scene, sheet: SkinSheet) {
  const animKey = (name: AnimName, dir: KidDirection) => `${sheet.texture}-${name}-${dir}`;
  KID_DIRECTIONS.forEach((dir, row) => {
    const frame = (i: number) => row * COLUMNS + i;
    const range = (name: AnimName) =>
      Array.from({ length: ANIM[name].count }, (_, i) => ({
        key: sheet.texture,
        frame: frame(ANIM[name].start + i),
      }));

    const add = (config: Phaser.Types.Animations.Animation) => {
      if (!scene.anims.exists(config.key!)) scene.anims.create(config);
    };

    add({ key: animKey("walk", dir), frames: range("walk"), frameRate: WALK_FPS, repeat: -1 });
    add({ key: animKey("run", dir), frames: range("run"), frameRate: RUN_FPS, repeat: -1 });
    add({ key: animKey("breathe", dir), frames: range("breathe"), frameRate: 3, repeat: -1 });
    add({ key: animKey("idle", dir), frames: range("idle"), frameRate: 4, repeat: -1 });

    // Tag swing: neutral, wind-up, reach, MOST extended (held), reach, recover.
    // The extra `duration` on the 4th frame holds the arm fully outstretched
    // so the reach reads clearly at game speed.
    const tagFrames = range("tag").map((f, i) => ({
      ...f,
      duration: i === 3 ? 170 : i === 2 || i === 4 ? 30 : 0,
    }));
    add({ key: animKey("tag", dir), frames: tagFrames, frameRate: 16, repeat: 0 });
  });
}

export type KidRole = "self" | "it" | "bot" | "human";

/** Lines of the label stack above the head, bottom to top. */
const LABEL_LINES = ["name", "you", "it"] as const;
type LabelLine = (typeof LABEL_LINES)[number];

const LABEL_STYLE: Phaser.Types.GameObjects.Text.TextStyle = {
  fontFamily: "system-ui, sans-serif",
  fontStyle: "bold",
  stroke: "#10131a",
  strokeThickness: 4,
};
const LABEL_LOOK: Record<LabelLine, { text: string; style: Phaser.Types.GameObjects.Text.TextStyle }> = {
  name: { text: "", style: { ...LABEL_STYLE, fontSize: "13px", color: "#ffffff" } },
  you: { text: "YOU", style: { ...LABEL_STYLE, fontSize: "12px", color: "#7dd3fc" } },
  it: { text: "IT", style: { ...LABEL_STYLE, fontSize: "14px", color: "#ff5c5c" } },
};
/** Lines overlap by this much (their stroke padding) for a tight stack. */
const LABEL_TIGHTEN = 5;
/** Gap between the top of the head and the bottom label (px). */
const LABEL_GAP = 2;
/** Extra space under IT so it doesn't touch the YOU / name line below (px). */
const IT_GAP = 4;
/** Keep the top of the label stack at least this far below the world top. */
const LABEL_MIN_TOP = 2;

const ROLE_COLORS: Record<KidRole, number> = {
  self: 0x38bdf8, // blue
  it: 0xef4444, // red
  bot: 0xa78bfa, // purple
  human: 0xf59e0b, // amber
};

/**
 * One on-screen kid: sprite + coloured ground ring + a label stack above
 * the head (top to bottom: IT if it, YOU for the local player, name; lines
 * that don't apply collapse).
 * `x`/`y` are the logical (server) position; the sprite is drawn with its
 * feet slightly below that point and depth-sorted by y.
 */
export class KidAvatar {
  readonly sprite: Phaser.GameObjects.Sprite;
  /** Coloured ellipse under the feet; stays at the logical position (camera target). */
  readonly shadow: Phaser.GameObjects.Ellipse;
  private readonly labels: Record<LabelLine, Phaser.GameObjects.Text>;
  private readonly showLabel: Record<LabelLine, boolean> = { name: true, you: false, it: false };

  x: number;
  y: number;
  facing = Math.PI / 2; // face the camera (south) until we know better
  moving = false;
  running = false;

  private role: KidRole | null = null;
  private tagging = false;
  private tagFacing: number | null = null;
  private lunge = { t: 0 };
  private lungeTween: Phaser.Tweens.Tween | null = null;
  private readonly feetOffset: number;
  private skin: Skin = DEFAULT_SKIN;

  /**
   * @param radius the player's collision radius on the server; sizes the
   *   ground ring and places the feet just below the logical centre.
   */
  constructor(
    private readonly scene: Phaser.Scene,
    x: number,
    y: number,
    radius: number,
    name: string
  ) {
    this.x = x;
    this.y = y;
    this.feetOffset = radius * FEET_OFFSET_RADII;

    this.shadow = scene.add.ellipse(
      x,
      y + this.feetOffset,
      radius * 2 * SIZE,
      radius * 0.75 * SIZE,
      0x000000,
      0.45
    );
    this.shadow.setDepth(1);

    const sheet = SKINS[this.skin];
    this.sprite = scene.add.sprite(x, y + this.feetOffset, sheet.texture, 2 * COLUMNS + ANIM.breathe.start);
    this.sprite.setOrigin(0.5, sheet.baselineY / sheet.frameHeight);
    this.sprite.setScale(KID_SCALE);

    const label = (line: LabelLine) =>
      scene.add.text(x, y, LABEL_LOOK[line].text, LABEL_LOOK[line].style).setOrigin(0.5, 1);
    this.labels = { name: label("name"), you: label("you"), it: label("it") };
    this.labels.name.setText(name);

    this.sprite.on(
      Phaser.Animations.Events.ANIMATION_COMPLETE,
      (anim: Phaser.Animations.Animation) => {
        if (animOf(anim.key) === "tag") this.endTag();
      }
    );

    this.update();
  }

  setRole(role: KidRole) {
    if (role === this.role) return;
    this.role = role;
    const color = ROLE_COLORS[role];
    this.shadow.setFillStyle(color, 0.35);
    this.shadow.setStrokeStyle(2, color, 0.95);
    // A light red wash on the kid makes IT readable even without the ring.
    if (role === "it") this.sprite.setTint(0xffc4c4);
    else this.sprite.clearTint();
  }

  /**
   * Switch outfit (e.g. James <-> Banana James). Keeps whatever the kid is
   * doing: the same animation, direction and progress continue in the new
   * skin's sheet.
   */
  setSkin(skin: Skin) {
    if (skin === this.skin || !SKINS[skin]) return;
    const current = this.sprite.anims.currentAnim?.key;
    const progress = this.sprite.anims.isPlaying ? this.sprite.anims.getProgress() : 0;
    this.skin = skin;
    const sheet = SKINS[skin];
    this.sprite.setTexture(sheet.texture, this.sprite.frame.name);
    this.sprite.setOrigin(0.5, sheet.baselineY / sheet.frameHeight);
    const [, name, dir] = current?.split("-") ?? [];
    if (name && dir) {
      this.sprite.anims.play(animKey(name as AnimName, dir as KidDirection, skin));
      if (progress) this.sprite.anims.setProgress(progress);
    }
    this.update();
  }

  get currentSkin(): Skin {
    return this.skin;
  }

  /** Height of the art above the feet in world px (hair top or banana stem). */
  private get artHeight(): number {
    return SKINS[this.skin].artHeight * KID_SCALE;
  }

  /** Label stack contents: name, plus the YOU / IT lines when they apply. */
  setLabels(labels: { name: string; you: boolean; it: boolean }) {
    if (this.labels.name.text !== labels.name) this.labels.name.setText(labels.name);
    this.showLabel.name = labels.name !== "";
    this.showLabel.you = labels.you;
    this.showLabel.it = labels.it;
  }

  /** World-space box around the visible kid: body, ring and label stack. */
  get bounds(): Phaser.Geom.Rectangle {
    const feetY = this.y + this.feetOffset;
    let left = this.x - FRAME_W * KID_SCALE * 0.3;
    let right = this.x + FRAME_W * KID_SCALE * 0.3;
    for (const line of LABEL_LINES) {
      if (!this.showLabel[line]) continue;
      const half = this.labels[line].width / 2;
      left = Math.min(left, this.x - half);
      right = Math.max(right, this.x + half);
    }
    const top = Math.min(this.labelTop, feetY - this.artHeight);
    const bottom = feetY + this.shadow.height / 2;
    return new Phaser.Geom.Rectangle(left, top, right - left, bottom - top);
  }

  /** World-space top of the label stack (for tests / layout checks). */
  get labelTop(): number {
    let top = this.labels.name.y;
    for (const line of LABEL_LINES) {
      if (this.showLabel[line]) top = Math.min(top, this.labels[line].y - this.labels[line].height);
    }
    return top;
  }

  /**
   * Play the tag (arm reach) once, in the direction the kid is facing right
   * now. `towardAngle` locks a different facing (a remote kid swinging at
   * someone). Walking does not restart or replace this clip.
   */
  playTag(towardAngle?: number) {
    if (this.tagging) return;
    this.tagging = true;
    this.tagFacing = towardAngle ?? this.facing;
    this.sprite.anims.play(
      nextAvatarAnim({
        texture: SKINS[this.skin].texture,
        facing: this.facing,
        moving: this.moving,
        running: this.running,
        tagging: true,
        tagFacing: this.tagFacing,
      })
    );

    // Small forward lunge in the facing direction, synced to the reach.
    this.lungeTween?.stop();
    this.lunge.t = 0;
    this.lungeTween = this.scene.tweens.add({
      targets: this.lunge,
      t: 1,
      duration: 190,
      delay: 90,
      ease: "Quad.easeOut",
      yoyo: true,
      hold: 120,
      onComplete: () => {
        this.lunge.t = 0;
      },
    });
  }

  get isTagging() {
    return this.tagging;
  }

  /** World Y of the feet (ground contact), used for depth / occlusion. */
  get feetY(): number {
    return this.y + this.feetOffset;
  }

  private endTag() {
    this.tagging = false;
    this.tagFacing = null;
  }

  /** Does world point (x, y) land on this kid's body (for tap-to-tag)? */
  hitTest(x: number, y: number): boolean {
    const feetY = this.y + this.feetOffset;
    const height = FRAME_H * KID_SCALE * 0.9;
    const halfWidth = FRAME_W * KID_SCALE * 0.3;
    return Math.abs(x - this.x) <= halfWidth && y <= feetY + 8 && y >= feetY - height;
  }

  /** Call every frame after updating x/y/facing/moving/running. */
  update() {
    const facing = this.tagFacing ?? this.facing;
    const key = nextAvatarAnim({
      texture: SKINS[this.skin].texture,
      facing: this.facing,
      moving: this.moving,
      running: this.running,
      tagging: this.tagging,
      tagFacing: this.tagFacing,
    });

    if (this.tagging) {
      // The swing wins until its clip finishes. A walk / run / turn must
      // not replace it, including a movement clip that started this frame.
      if (this.sprite.anims.currentAnim?.key !== key) this.sprite.anims.play(key);
    } else if (this.moving) {
      const current = this.sprite.anims.currentAnim?.key;
      if (current !== key) {
        // Keep the stride phase when turning or switching walk <-> run.
        const was = animOf(current);
        const progress = was === "walk" || was === "run" ? this.sprite.anims.getProgress() : 0;
        this.sprite.anims.play(key);
        if (progress) this.sprite.anims.setProgress(progress);
      }
    } else {
      this.sprite.anims.play(key, true);
    }

    const lunge = TAG_LUNGE * this.lunge.t;
    const lx = Math.cos(facing) * lunge;
    const ly = Math.sin(facing) * lunge * 0.6;

    const feetY = this.y + this.feetOffset;
    this.shadow.setPosition(this.x, feetY);
    this.sprite.setPosition(this.x + lx, feetY + ly);
    // Lower on screen = drawn in front.
    // Same depth band as schoolyard props (trees / bushes / fence), so a
    // kid north of a trunk sorts behind it. Labels sit just above the
    // sprite so a translucent canopy can cover them too (still readable).
    const depth = 10 + feetY / 10;
    this.sprite.setDepth(depth);
    let labelY = feetY - this.artHeight - LABEL_GAP;
    const firstY = labelY;
    let labelDepth = depth + 0.05;
    for (const line of LABEL_LINES) {
      const text = this.labels[line];
      text.setVisible(this.showLabel[line]);
      if (!this.showLabel[line]) continue;
      if (line === "it" && labelY !== firstY) labelY -= IT_GAP;
      text.setPosition(this.x, labelY);
      text.setDepth(labelDepth);
      labelDepth += 0.01;
      labelY -= text.height - LABEL_TIGHTEN;
    }
    // The camera can't scroll above y = 0: at the top wall, the tallest skin
    // with IT + YOU would poke off screen, so nudge the stack down onto the
    // head instead (only ever a pixel or two).
    const overflow = LABEL_MIN_TOP - (labelY - LABEL_TIGHTEN);
    if (overflow > 0) {
      for (const line of LABEL_LINES) {
        if (this.showLabel[line]) this.labels[line].y += overflow;
      }
    }
  }

  destroy() {
    this.lungeTween?.stop();
    this.sprite.destroy();
    this.shadow.destroy();
    for (const line of LABEL_LINES) this.labels[line].destroy();
  }
}
